# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_layout_proto/ping_pong.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc_layout_proto/ping_pong.proto',
  package='ping_pong',
  syntax='proto3',
  serialized_pb=_b('\n!grpc_layout_proto/ping_pong.proto\x12\tping_pong\"\x19\n\nRequestMsg\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1a\n\x0bResponseMsg\x12\x0b\n\x03msg\x18\x01 \x01(\t2J\n\x0fPingPongService\x12\x37\n\x04\x43\x61ll\x12\x15.ping_pong.RequestMsg\x1a\x16.ping_pong.ResponseMsg\"\x00\x42\x0fZ\r./proto;hellob\x06proto3')
)




_REQUESTMSG = _descriptor.Descriptor(
  name='RequestMsg',
  full_name='ping_pong.RequestMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='ping_pong.RequestMsg.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=73,
)


_RESPONSEMSG = _descriptor.Descriptor(
  name='ResponseMsg',
  full_name='ping_pong.ResponseMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='ping_pong.ResponseMsg.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['RequestMsg'] = _REQUESTMSG
DESCRIPTOR.message_types_by_name['ResponseMsg'] = _RESPONSEMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestMsg = _reflection.GeneratedProtocolMessageType('RequestMsg', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTMSG,
  __module__ = 'grpc_layout_proto.ping_pong_pb2'
  # @@protoc_insertion_point(class_scope:ping_pong.RequestMsg)
  ))
_sym_db.RegisterMessage(RequestMsg)

ResponseMsg = _reflection.GeneratedProtocolMessageType('ResponseMsg', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEMSG,
  __module__ = 'grpc_layout_proto.ping_pong_pb2'
  # @@protoc_insertion_point(class_scope:ping_pong.ResponseMsg)
  ))
_sym_db.RegisterMessage(ResponseMsg)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\r./proto;hello'))

_PINGPONGSERVICE = _descriptor.ServiceDescriptor(
  name='PingPongService',
  full_name='ping_pong.PingPongService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=103,
  serialized_end=177,
  methods=[
  _descriptor.MethodDescriptor(
    name='Call',
    full_name='ping_pong.PingPongService.Call',
    index=0,
    containing_service=None,
    input_type=_REQUESTMSG,
    output_type=_RESPONSEMSG,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PINGPONGSERVICE)

DESCRIPTOR.services_by_name['PingPongService'] = _PINGPONGSERVICE

# @@protoc_insertion_point(module_scope)
